### ISSUE TITLE
include a command to delete used key

### ISSUE THREAD

**Issue by aaannndddyyy** [kfogel/OneTime#20]
Please include a command that deletes already used key material.
It is unsave to have used keys lying around. Perfect forward secrecy wanted.
Deleting it should be easy. 
Of course, for convenience, some prefer to keep them, or if the key is on a non-writeable medium, 
that's why only a command and not a default action.
If the key file is very big, it may last quite some time.
Ideally wipe it.

**Comment by kfogel** [comment]
This is an interesting idea.  It would actually be tricky to implement, because OneTime assumes that it is using only a small portion (per message) of a large pad file.  That's what the `pad-records` file keeps track of, on a per-padfile basis.  We can zero out a portion of a file, but if we make a mistake, then we've really messed someone up.  I'd prefer not to add such a risky feature to OneTime.  I think most users are not expecting their encryption program to have any effect on their key material, especially in a one-time pad system, and I don't want to surprise them.

Also, if we delete used key material, then the sender can no longer read their own sent message.
